-- require("themes.kanagawa")
-- require("themes.doom-one")
-- require("themes.rose-pine")
-- require("themes.tokyonight")
require("themes.cyberdream")
-- require("themes.onedark")
-- require("themes.vscode")
